AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Stratton_Oakmont

  Sample SAM Template for Stratton_Oakmont

  '
Globals:
  Function:
    Timeout: 900
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  FileUploadTriggerSQS:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: file-upload-trigger
      VisibilityTimeout: 960
    Metadata:
      SamResourceId: FileUploadTriggerSQS
  FileUploadTriggerLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://find-face-code-build/2d0510a758d06616f6e08e1f948938da
      Handler: fileUploadTrigger.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64
      Events:
        EventTrigger:
          Type: SQS
          Properties:
            Queue:
              Fn::GetAtt:
              - FileUploadTriggerSQS
              - Arn
            BatchSize: 10
            Enabled: false
    Metadata:
      SamResourceId: FileUploadTriggerLambda
  ImageFolder:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: face-clustering-img-folder9598
    Metadata:
      SamResourceId: ImageFolder
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
    Metadata:
      SamResourceId: ApplicationResourceGroup
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
    Metadata:
      SamResourceId: ApplicationInsightsMonitoring
Outputs:
  FileUploadTriggerSQSOutput:
    Description: ARN of source queue
    Value:
      Fn::GetAtt:
      - FileUploadTriggerSQS
      - Arn
  ImageFolderOutput:
    Description: S3 Bucket Name
    Value:
      Ref: ImageFolder
