[tool.poetry]
name = "stratton-oakmont"
version = "0.1.0"
description = ""
authors = ["Vasanth-12 <vasanth.dpalanisamy@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
